appbiblioteca/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import home, login_view, logout_view
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('livros/', include('livros.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('usuarios/', include('usuarios.urls')),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livros/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.livros, name='livros'),
    path('gerenciarLivros', views.gerenciar_livros, name='gerenciar_livros'),
    path('gerenciarLivros/ordenar/<ordem>', views.ordenar_livros, name='ordenar_livros'),
    path('cadastro', views.cadastrar_livro, name='cadastrar_livro'),
    path('editar/<int:id>', views.editar_livro, name='editar_livro'),
    path('deletar/<int:id>', views.deletar_livro, name='deletar_livro'),
    path('livro_detalhes/<int:id>', views.livro_detalhes, name='livro_detalhes'),
  

    path('emprestimos', views.gerenciar_emprestimos, name='gerenciar_emprestimos'),
    path('emprestimos/selecionar-livro', views.selecionar_livro_emprestimo, name='selecionar_livro_emprestimo'),
    path('emprestimos/<int:id>/selecionar-cliente', views.selecionar_cliente_emprestimo, name='selecionar_cliente_emprestimo'),
    path('emprestimos/realizar/<int:livro_id>/<int:cliente_id>', views.realizar_emprestimo, name='realizar_emprestimo'),
    path('emprestimos/deletar/<int:id>', views.deletar_emprestimo, name='deletar_emprestimo'),
    path('emprestimos/<int:id_emprestimo>/editar', views.editar_emprestimo, name='editar_emprestimo'),
    path('emprestimos/<int:id_emprestimo>/renovar', views.renovar, name='renovar'),
    path('emprestimos/<int:id_emprestimo>/devolver', views.devolver_emprestimo, name='devolver_emprestimo'),

    path('reservas/', views.gerenciar_reservas, name='gerenciar_reservas'),
    path('reservas/livro/', views.selecionar_livro_reserva, name='selecionar_livro_reserva'),
    path('reservas/cliente/<int:id>/', views.selecionar_cliente_reserva, name='selecionar_cliente_reserva'),
    path('reservas/finalizar/<int:livro_id>/<int:cliente_id>/', views.realizar_reserva, name='realizar_reserva'),
    path('reservas/deletar/<int:id>/', views.deletar_reserva, name='deletar_reserva'),

    path('infracaoes', views.infracoes, name='infracoes'),
    path('infracao/<int:emprestimo_id>', views.registrar_infracao, name='registrar_infracao'),
    path('infracao/<int:id>/deletar', views.deletar_infracao, name='deletar_infracao'),
    path('relatorios/CLIENTE', views.relatorio_emprestimos_cliente, name='relatorio_emprestimos_cliente'),
    path('relatorios/LIVRO', views.relatorio_livros_mais_emprestados, name='relatorio_livros_mais_emprestados'),
]

livros/models.py
from django.db import models
from usuarios.models import Cliente
from datetime import datetime
from stdimage.models import StdImageField

GENEROS = [
        ('FICCAO', 'Ficção'),
        ('ROMANCE', 'Romance'),
        ('AVENTURA', 'Aventura'),
        ('FANTASIA', 'Fantasia'),
        ('BIOFRAFIA', 'Biografia'),
        ('AUTOAJUDA', 'Autoajuda'),
        ('TECNICO', 'Técnico'),
    ]
STATUS_EMPRESTIMO = [
    ('EM_ANDAMENTO', 'Em Andamento'),
    ('FINALIZADO', 'Finalizado'),
    ('EM_ATRASO', 'Em Atraso')
]
STATUS_RESERVA = [
    ('AGUARDANDO','Aguardando'),
    ('FINALIZADA','Finalizada')
]
CHOICE_OCORRENCIA = [
    ('PERDIDO', 'Perdido'),
    ('DANIFICADO', 'Danificado')
]
class Livro(models.Model):
    nome = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    descricao = models.TextField()
    ano_publicacao = models.IntegerField(default=datetime.now().year)
    foto = StdImageField(
        upload_to='fotos/alunos',
        variations={'thumb': (150, 150), 'medium': (300, 300)},
        blank=True,
        null=True
    )

    isbn = models.CharField(max_length=17, blank=True, null=True, unique=True,
                            help_text="ISBN do livro (ex: 978-3-16-148410-0)")
    genero = models.CharField(max_length=20, choices=GENEROS, default='ficcao')
    quantidade = models.PositiveIntegerField(default=0)
    def exemplares_disponiveis(self):
        emprestimos_ativos = self.emprestimo_set.exclude(status='FINALIZADO').count()
        return max(self.quantidade - emprestimos_ativos, 0)
    def esta_disponivel_para_cliente(self, cliente):
        if self.exemplares_disponiveis() <= 0:
            return False
        primeira_reserva = self.reserva_set.filter(status='AGUARDANDO').order_by('data_solicitacao').first()
        if not primeira_reserva:
            return True
        return primeira_reserva.cliente == cliente
    def esta_reservado_para_outro(self, cliente):
        reserva = self.reserva_set.filter(status='AGUARDANDO').order_by('data_solicitacao').first()
        return reserva and reserva.cliente != cliente
    def esta_reservado_para_alguem(self):
        return self.reserva_set.filter(status='AGUARDANDO').exists()
    def proxima_reserva(self):
        return self.reserva_set.filter(status='AGUARDANDO').order_by('data_solicitacao').first()
    def exemplares_nao_reservados(self):
        reservas_ativas = self.reserva_set.filter(status='AGUARDANDO').count()
        return max(self.exemplares_disponiveis() - reservas_ativas, 0)
    def pode_ser_reservado(self):
        return self.exemplares_nao_reservados() <= 0
    def __str__(self):
        return self.nome
    def save(self, *args, **kwargs):
        if self.nome:
            self.nome = self.formatar_nome_curso(self.nome)
        super().save(*args, **kwargs)

    def formatar_nome_curso(self, nome):
        partes = nome.lower().split()
        minusculas = ['da', 'de', 'do', 'das', 'dos', 'e',
                      'em', 'a', 'o', 'as', 'os', 'para', 'com']

        return ' '.join([
            p if p in minusculas else p.capitalize()
            for p in partes
        ])
class Emprestimo(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro,on_delete=models.CASCADE)
    data_emprestimo= models.DateField()
    data_devolucao = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_EMPRESTIMO, default='EM_ANDAMENTO')

    def __str__(self):
        return f'{self.cliente.nome} locou o livro {self.livro.nome} no dia {self.data_emprestimo} e devolve no dia {self.data_devolucao} - Status - {self.status}'

class Reserva(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro,on_delete=models.CASCADE)
    data_solicitacao = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_RESERVA, default='AGUARDANDO')

    def __str__(self):
        return f'Cliente {self.cliente.nome} reservou o livro {self.livro.nome} no dia {self.data_solicitacao}'
class Infracao(models.Model):
    emprestimo = models.ForeignKey(Emprestimo, on_delete=models.CASCADE)
    ocorrencia = models.CharField(max_length=20, choices=CHOICE_OCORRENCIA)
    bloquear_cliente = models.BooleanField(default=True)
    data_infracao = models.DateField(auto_now_add=True)

livros/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.utils.dateparse import parse_date
from datetime import date,datetime
from django.utils.timezone import localdate
from .models import Livro, Emprestimo, Reserva, Infracao
from usuarios.models import Cliente
from .forms import LivroForm, RenovarEmprestimoForm, InfracaoForm
from django.core.mail import send_mail
from django.utils.timezone import localdate
from datetime import date, datetime, timedelta

ORDENACAO_LIVROS_LOOKUP = {
    'nome': 'nome',
    'autor': 'autor',
    'descricao': 'descricao',
    'ano_publicacao': 'ano_publicacao',
    'quantidade':'quantidade',
    'isbn':'isbn',
    'genero':'genero'
}

def index(request):
    return render(request, 'livros/index.html')

def livros(request):
    livros = Livro.objects.all()
    dados = {
        'livros':livros
    }
    return render(request, 'livros/lista_livros.html', dados)
def livro_detalhes(request, id):
    livro = get_object_or_404(Livro, id=id)
    return render(request, 'livros/detalhe_livro.html', {'livro': livro})

def gerenciar_livros(request):
    busca = request.GET.get('busca', '')
    livros = Livro.objects.all()
    if busca:
        livros = livros.filter(nome__icontains=busca)
    dados = {
        'livros': livros,
        'query': busca,
    }
    return render(request, 'livros/gerenciar_livros.html', dados)
def ordenar_livros(request, ordem):
    busca = request.GET.get('busca', '')
    direcao = request.GET.get('ordenacao', 'asc')

    livros = Livro.objects.all()
    if busca:
        livros = livros.filter(nome__icontains=busca)
    campo_ordenacao = ORDENACAO_LIVROS_LOOKUP.get(ordem)
    if direcao=='desc':
        campo_ordenacao = f'-{campo_ordenacao}'

    print(f'campo ordenadao: {campo_ordenacao}')
    livros = livros.order_by(campo_ordenacao)
    dados = {
        'livros': livros,
        'query': busca,
    }
    return render(request, 'livros/gerenciar_livros.html', dados)
def cadastrar_livro(request):
    if request.method == 'POST':
        form = LivroForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('gerenciar_livros')  # ajuste para a sua URL de destino
    else:
        form = LivroForm()

    return render(request, 'livros/cadastrar_livro.html', {'form': form})
def editar_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    if request.method == 'POST':
        form = LivroForm(request.POST,request.FILES, instance=livro)
        if form.is_valid():
            form.save()
            return redirect('gerenciar_livros')
    else:
        form = LivroForm(instance=livro)
    return render(request, 'livros/cadastrar_livro.html', {'form': form})

def deletar_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    livro.delete()
    return redirect('gerenciar_livros')

@login_required
def gerenciar_emprestimos(request):
    busca = request.GET.get('busca', '')
    if busca:
        emprestimos = Emprestimo.objects.filter(
            Q(cliente__nome__icontains=busca) | Q(livro__nome__icontains=busca)
        )
    else:
        emprestimos = Emprestimo.objects.all()
    return render(request, 'emprestimos/gerenciar_emprestimos.html', {'emprestimos': emprestimos})
@login_required
def selecionar_livro_emprestimo(request):
    busca = request.GET.get('busca','')
    livros = Livro.objects.all()
    if busca:
        livros = livros.filter(nome__icontains=busca)
    dados = {
        'livros':livros,
        'redirect':'selecionar_cliente_emprestimo'
    }

    return render(request, 'livros/selecionar_livro.html', dados)
@login_required
def selecionar_cliente_emprestimo(request, id):
    livro = get_object_or_404(Livro, id=id)
    if livro.exemplares_disponiveis() <= 0:
        messages.error(request, 'Não existem exemplares disponíveis da obra selecionada.')
        return redirect('selecionar_livro_emprestimo')
    clientes = Cliente.objects.all()
    for cliente in clientes:
        cliente.tem_prioridade = livro.esta_disponivel_para_cliente(cliente)
    dados = {
        'livro': livro,
        'clientes': clientes,
        'redirect':'realizar_emprestimo'
    }

    print(dados)
    return render(request, 'livros/selecionar_cliente.html', dados)

@login_required
def realizar_emprestimo(request, livro_id, cliente_id):
    livro = get_object_or_404(Livro, id=livro_id)
    cliente = get_object_or_404(Cliente, id=cliente_id)
    reserva_ativa = Reserva.objects.filter(livro=livro, status='AGUARDANDO').order_by('data_solicitacao').first()
    if reserva_ativa and reserva_ativa.cliente != cliente:
        messages.error(request, f'Este livro está reservado para outro cliente: {reserva_ativa.cliente.nome}.')
        return redirect('gerenciar_emprestimos')

    if request.method == 'POST':
        data_emprestimo = request.POST.get('data_emprestimo')
        data_devolucao = request.POST.get('data_devolucao')

        # Impedir empréstimo se houver reserva de outro cliente
        reserva_ativa = Reserva.objects.filter(livro=livro, status='AGUARDANDO').order_by('data_solicitacao').first()
        if reserva_ativa and reserva_ativa.cliente != cliente:
            messages.error(request, f'Este livro está reservado para outro cliente: {reserva_ativa.cliente.nome}.')
            return redirect('gerenciar_emprestimos')

        erros = []
        if not data_emprestimo:
            erros.append('Data de empréstimo é obrigatória.')
        if not data_devolucao:
            erros.append('Data de devolução é obrigatória.')

        if data_emprestimo and data_devolucao:
            try:
                dt_emprestimo = datetime.strptime(data_emprestimo, '%Y-%m-%d').date()
                dt_devolucao = datetime.strptime(data_devolucao, '%Y-%m-%d').date()
                hoje = localdate()
                if dt_emprestimo < hoje:
                    erros.append('A data de empréstimo não pode ser anterior a hoje.')
                if dt_devolucao < hoje:
                    erros.append('A data de devolução não pode ser anterior a hoje.')
                if dt_devolucao <= dt_emprestimo:
                    erros.append('Data de devolução deve ser posterior à data de empréstimo.')
            except ValueError:
                erros.append('Formato de data inválido. Use yyyy-mm-dd.')

        if erros:
            for erro in erros:
                messages.error(request, erro)
            return render(request, 'emprestimos/finalizar_emprestimo.html', {
                'livro': livro,
                'cliente': cliente,
                'data_emprestimo': data_emprestimo,
                'data_devolucao': data_devolucao,
            })

        Emprestimo.objects.create(
            cliente=cliente,
            livro=livro,
            data_emprestimo=data_emprestimo,
            data_devolucao=data_devolucao,
            status='EM_ANDAMENTO'
        )
        # Finaliza reserva associada ao cliente
        reserva = Reserva.objects.filter(cliente=cliente, livro=livro, status='AGUARDANDO').first()
        if reserva:
            reserva.status = 'FINALIZADA'
            reserva.save()
        return redirect('gerenciar_emprestimos')

    hoje = localdate()
    devolucao_sugerida = hoje + timedelta(days=7)
    return render(request, 'emprestimos/finalizar_emprestimo.html', {
        'livro': livro,
        'cliente': cliente,
        'data_emprestimo': hoje.strftime('%Y-%m-%d'),
        'data_devolucao': '',
    })
@login_required
def editar_emprestimo(request, id_emprestimo):
    emprestimo = get_object_or_404(Emprestimo, id=id_emprestimo)
    

    if request.method == 'POST':
        data_emprestimo = request.POST.get('data_emprestimo')
        data_devolucao = request.POST.get('data_devolucao')
        # Sua validação aqui
        erros = []
        if not data_emprestimo:
            erros.append('Data de empréstimo é obrigatória.')
        if not data_devolucao:
            erros.append('Data de devolução é obrigatória.')
        if data_emprestimo and data_devolucao:
            try:
                dt_emprestimo = datetime.strptime(data_emprestimo, '%Y-%m-%d').date()
                dt_devolucao = datetime.strptime(data_devolucao, '%Y-%m-%d').date()
              
                hoje = localdate()
                if dt_emprestimo < hoje:
                    erros.append('A data de empréstimo não pode ser anterior a hoje.')

                if dt_devolucao < hoje:
                    erros.append('A data de devolução não pode ser anterior a hoje.')

                if dt_devolucao <= dt_emprestimo:
                    erros.append('Data de devolução deve ser posterior à data de empréstimo.')

            except ValueError:
                erros.append('Formato de data inválido. Use yyyy-mm-dd.')
        if erros:
            for erro in erros:
                messages.error(request, erro)
            return render(request, 'emprestimos/finalizar_emprestimo.html', {
                'livro': emprestimo.livro,
                'cliente': emprestimo.cliente,
                'data_emprestimo': data_emprestimo,
                'data_devolucao': data_devolucao,
            })
        emprestimo.data_emprestimo = data_emprestimo
        emprestimo.data_devolucao = data_devolucao
        emprestimo.save()
        return redirect('gerenciar_emprestimos')

  
    return render(request, 'emprestimos/finalizar_emprestimo.html', {
        'livro': emprestimo.livro,
        'cliente': emprestimo.cliente,
        'data_emprestimo': emprestimo.data_emprestimo.strftime('%Y-%m-%d'),
        'data_devolucao': emprestimo.data_devolucao.strftime('%Y-%m-%d'),
    })
@login_required
def gerenciar_emprestimos(request):
    busca = request.GET.get('busca', '')
    if busca:
        emprestimos = Emprestimo.objects.filter(

livros/templates/emprestimos/confirmar_devolucao.html
{% extends 'base.html' %}

{% block title %}Devolver Livro{% endblock %}

{% block content %}
<div class="container my-4">

  <!-- Card do livro -->
  <div class="card shadow-sm mb-4 p-3">
    <div class="d-flex flex-column flex-md-row align-items-center">
      <div style="min-width: 200px; max-width: 200px;">
        {% if livro.foto.thumb.url %}
        <img src="{{ livro.foto.thumb.url }}" alt="Capa do livro {{ livro.nome }}" class="img-fluid"
          style="max-height: 300px; object-fit: contain;">
        {% else %}
        <div class="bg-light d-flex justify-content-center align-items-center" style="height: 300px;">
          <span class="text-muted">Sem imagem disponível</span>
        </div>
        {% endif %}
      </div>
      <div class="ms-md-4 mt-3 mt-md-0 flex-grow-1">
        <h2>{{ livro.nome }}</h2>
        <h5 class="text-muted">Autor: {{ livro.autor }}</h5>
        <p>{{ livro.descricao }}</p>
        <p class="text-muted">Publicado em: {{ livro.ano_publicacao }}</p>
      </div>
    </div>
  </div>

  <!-- Cliente + Formulário -->
  <div class="card shadow-sm p-3 mb-4">
    <h4 class="mb-3">Confirmar devolução do empréstimo de livro</h4>

    <p><strong>Cliente:</strong> {{ cliente.nome }}</p>
    <p><strong>CPF:</strong> {{ cliente.cpf }}</p>

    {% include 'messages.html' %}

    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_data_devolucao" class="form-label">Data da Devolução</label>
        <input type="date" name="data_devolucao" id="id_data_devolucao" class="form-control"
          value="{{ data_devolucao|default:'' }}">
      </div>

      <button type="submit" class="btn btn-primary">Confirmar Devolução</button>
      <a href="{% url 'gerenciar_emprestimos' %}" class="btn btn-secondary">Voltar</a>
    </form>
  </div>

</div>
{% endblock %}

livros/templates/emprestimos/confirmar_renovacao.html
{% extends 'base.html' %}
{% block title %}Confirmar Renovação{% endblock %}
{% block content %}
<div class="container mt-4">
    <h4>Confirmar renovação de empréstimo</h4>
    <p><strong>Livro:</strong> {{ livro.nome }}</p>
    <p><strong>Cliente:</strong> {{ cliente.nome }}</p>

    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="{{ form.nova_data_devolucao.id_for_label }}" class="form-label">
                {{ form.nova_data_devolucao.label }}
            </label>
            {{ form.nova_data_devolucao }}

            {% if form.nova_data_devolucao.errors %}
            <div class="text-danger mt-1">
                {{ form.nova_data_devolucao.errors }}
            </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Renovar</button> 
        <a href="{% url 'gerenciar_emprestimos' %}" class="btn btn-secondary btn-md">Voltar</a>
    </form>
    {% include 'messages.html' %}

</div>
{% endblock %}

livros/templates/emprestimos/finalizar_emprestimo.html
{% extends 'base.html' %}

{% block title %}Confirmar Empréstimo{% endblock %}

{% block content %}
<div class="container my-4">

  <!-- Card do livro -->
  <div class="card shadow-sm mb-4 p-3">
    <div class="d-flex flex-column flex-md-row align-items-center">
      <div style="min-width: 200px; max-width: 200px;">
        {% if livro.foto %}
        <img src="{{ livro.foto.thumb.url }}" alt="Capa do livro {{ livro.nome }}" class="img-fluid"
          style="max-height: 300px; object-fit: contain;">
        {% else %}
        <div class="bg-light d-flex justify-content-center align-items-center" style="height: 300px;">
          <span class="text-muted">Sem imagem disponível</span>
        </div>
        {% endif %}
      </div>
      <div class="ms-md-4 mt-3 mt-md-0 flex-grow-1">
        <h2>{{ livro.nome }}</h2>
        <h5 class="text-muted">Autor: {{ livro.autor }}</h5>
        <p>{{ livro.descricao }}</p>
        <p class="text-muted">Publicado em: {{ livro.ano_publicacao }}</p>
      </div>
    </div>
  </div>

  <!-- Cliente + Formulário -->
  <div class="card shadow-sm p-3 mb-4">
    <h4 class="mb-3">Confirmar Empréstimo</h4>

    <p><strong>Cliente:</strong> {{ cliente.nome }}</p>
    <p><strong>CPF:</strong> {{ cliente.cpf }}</p>

    {% include 'messages.html' %}

    <form method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="id_data_emprestimo" class="form-label">Data do Empréstimo</label>
        <input type="date" name="data_emprestimo" id="id_data_emprestimo" class="form-control"
          value="{{ data_emprestimo|default:'' }}">
      </div>

      <div class="mb-3">
        <label for="id_data_devolucao" class="form-label">Data da Devolução</label>
        <input type="date" name="data_devolucao" id="id_data_devolucao" class="form-control"
          value="{{ data_devolucao|default:'' }}">
      </div>

      <button type="submit" class="btn btn-primary">Confirmar Empréstimo</button>
      <a href="{% url 'gerenciar_emprestimos' %}" class="btn btn-secondary">Voltar</a>
    </form>
  </div>

</div>
{% endblock %}

livros/templates/emprestimos/gerenciar_emprestimos.html
{% extends 'base.html' %}

{% block title %}Gerenciar Emprestimos{% endblock %}

{% block content %}
<div class="my-4 px-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="h4 fw-bold mb-0">Lista de Empréstimos de livros</h1>
        <a href="{% url 'selecionar_livro_emprestimo' %}" class="btn btn-primary">Novo Emprestimo</a>
    </div>

    <form method="get" class="row g-2 mb-4">
        <div class="col-md-10">
            <input type="text" name="busca" placeholder="Buscar por cliente ou livro..." value="{{ request.GET.busca }}"
                class="form-control" />
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary w-100">Buscar</button>
        </div>
    </form>
    {% include 'messages.html' %}
    <div class="table-responsive" style="overflow: visible !important;">
        <table class="table table-bordered table-hover align-middle">
            <thead class="table-light">
                <tr>
                    <th>Cliente</th>
                    <th>Livro</th>
                    <th>Data do Emprestimo</th>
                    <th>Data de Devolução</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for emprestimo in emprestimos %}
                <tr>
                    <td>{{ emprestimo.cliente.nome }}</td>
                    <td>{{ emprestimo.livro.nome }}</td>
                    <td>{{ emprestimo.data_emprestimo |date:"d/m/Y" }}</td>
                    <td>{{ emprestimo.data_devolucao |date:"d/m/Y" }}</td>
                    <td>{{ emprestimo.get_status_display }}</td>
                    <td>

                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                data-bs-display="static" aria-expanded="false">
                                Ações
                            </button>
                            <ul class="dropdown-menu">
                                {% if emprestimo.status != 'FINALIZADO'%}
                                <li> <a href="{% url 'renovar' id_emprestimo=emprestimo.id %}" class="dropdown-item">
                                        Renovar
                                    </a></li>
                                <li> <a href="{% url 'devolver_emprestimo' id_emprestimo=emprestimo.id %}"
                                        class="dropdown-item">
                                        Devolver
                                    </a></li>
                                <li> <a href="{% url 'registrar_infracao' emprestimo_id=emprestimo.id %}"
                                        class="dropdown-item">
                                        Registrar Infração
                                    </a></li>
                                {% endif %}
                                <li>
                                    <form method="post" action="{% url 'deletar_emprestimo' emprestimo.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="dropdown-item"
                                            onclick="return confirm('Tem certeza que deseja excluir este emprestimo?');">
                                            Excluir
                                        </button>
                                    </form>
                                </li>


                            </ul>
                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center py-4">Nenhuma emprestimo cadastrada.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

livros/templates/emprestimos/selecionar_livro.html
{% extends 'base.html' %}

{% block title %}Cadastrar Emprestimo de Livro{% endblock %}

{% block content %}
<div class="my-4 px-5">
   <form method="get" class="row g-2 mb-4">
      <div class="col-md-10">
         <input type="text" name="busca" placeholder="Buscar por nome..." value="{{ request.GET.busca }}"
            class="form-control" />
      </div>
      <div class="col-md-2">
         <button type="submit" class="btn btn-primary w-100">Buscar</button>
      </div>
   </form>
    {% include 'messages.html' %}
   <div class="table-responsive">
      <table class="table table-bordered table-hover align-middle">
         <thead class="table-light">
            <tr>
               <th>
                  <div class="d-flex justify-content-between align-items-center">
                     <span>Nome</span>
                  </div>
               </th>

               <th>
                  <div class="d-flex justify-content-between align-items-center">
                     <span>Autor</span>

                  </div>
               </th>

               <th>
                  <div class="d-flex justify-content-between align-items-center">
                     <span>Descrição</span>

                  </div>
               </th>

               <th>
                  <div class="d-flex justify-content-between align-items-center">
                     <span>Publicado em</span>

                  </div>
               </th>

               <th>
                  <div class="d-flex justify-content-between align-items-center">
                     <span>Gênero</span>

                  </div>
               </th>

               <th>
                  <div class="d-flex justify-content-between align-items-center">
                     <span>Exemplares Disponíveis</span>
                  </div>
               </th>

               <th></th>
            </tr>

         </thead>
         <tbody>
            {% for livro in livros %}
            <tr>
               <td>{{ livro.nome }}</td>
               <td>{{ livro.autor }}</td>
               <td>{{ livro.descricao|truncatechars:50 }}</td>
               <td>{{ livro.ano_publicacao }}</td>
               <td>{{ livro.get_genero_display }}</td>
               <td>{{ livro.exemplares_disponiveis }}</td>
               <td>
                  <a href="{% url 'selecionar_cliente_emprestimo' livro.id %}" class="btn btn-primary btn-sm"">
                     Selecionar
                  </a>
               </td>
            </tr>
            {% empty %}
            <tr>
               <td colspan=" 7" class="text-center py-4">Nenhum livro cadastrado.
               </td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
      <a href="{% url 'gerenciar_emprestimos' %}" class="btn btn-secondary btn-sm">Voltar </a>

   </div>
</div>
{% endblock %}